# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example-app-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example-app-ios
  pod 'shared', :path => '../example-app/shared.podspec'
  pod 'Library', :path => '../library/library.podspec'

  target 'example-app-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'example-app-iosUITests' do
    # Pods for testing
  end

end
