# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'KiteUI Example App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KiteUI Example App
  pod 'shared', :path => '../example-app/shared.podspec'

  target 'KiteUI Example AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KiteUI Example AppUITests' do
    # Pods for testing
  end

end
